/*******************************************************************************
*   Copyright 2014 Analog Devices, Inc.
*
*   Licensed under the Apache License, Version 2.0 (the "License");
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the License at
*
*       http://www.apache.org/licenses/LICENSE-2.0
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
********************************************************************************/

package com.analog.lyric.dimple.events;

import org.eclipse.jdt.annotation.Nullable;

import com.analog.lyric.dimple.model.core.FactorGraph;
import com.analog.lyric.dimple.solvers.interfaces.ISolverFactorGraph;

/**
 * Base class for solver graph events.
 * <p>
 * This is for events generated by the graph as a whole, rather than individual
 * solver variables or factors.
 * <p>
 * @since 0.08
 * @author Christopher Barber
 */
public abstract class SolverGraphEvent extends SolverEvent
{
	private static final long serialVersionUID = 1L;

	/*--------------
	 * Construction
	 */
	
	protected SolverGraphEvent(ISolverFactorGraph source)
	{
		super(source);
	}
	
	/*---------------------
	 * EventObject methods
	 */
	
	@Override
	public ISolverFactorGraph getSource()
	{
		return (ISolverFactorGraph)source;
	}

	/*---------------------
	 * DimpleEvent methods
	 */
	
	@Override
	public @Nullable FactorGraph getModelObject()
	{
		return getSource().getModelObject();
	}
	
	/*---------------------
	 * SolverEvent methods
	 */

	@Override
	public ISolverFactorGraph getSolverObject()
	{
		return (ISolverFactorGraph)source;
	}
}
