function make(debug)

    %clear all;
    %clear classes;

    if nargin < 1
        debug = 0;
    end

    files = {'DimpleEntry.cpp',...
        'CombinationTableFactory.cpp',...
        'Domain.cpp',...
        'DoubleDomainItem.cpp',...
        'Function.cpp',...
        'IDomainItem.cpp',...
        'IFunctionPointer.cpp',...
        'INode.cpp',...
        'Variable.cpp',...
        'FactorGraph.cpp',...
        'DimpleException.cpp',...
        'Port.cpp',...
        'DimpleManager.cpp',...
        'MatlabFunctionPointer.cpp',...
        'MatrixDomainItem.cpp',...
        'MexHelpers.cpp',...
        };

    %TODO: have common file list
    if ~debug
        mex(files{:});
    else
        mex('-g',files{:});
    end
end
